#!/data/data/com.termux/files/usr/bin/bash

# --- CONFIGURASI ---
# Pilih salah satu remote (GitHub atau Azure)
# Uncomment salah satu, jangan dua-duanya sekaligus

# GitHub
REMOTE_URL="https://github.com/fareltampan/farelanakpintar.git"

# Azure
# REMOTE_URL="https://USERNAME@dev.azure.com/ORG_NAME/PROJECT_NAME/_git/REPO_NAME"

# Folder script
SCRIPT_DIR="$HOME/roblox-scripts"   # ganti sesuai folder kamu
COMMIT_MSG="Commit changes"

# --- MASUK FOLDER ---
cd "$SCRIPT_DIR" || { echo "Folder tidak ditemukan!"; exit 1; }

# --- Inisialisasi git kalau belum ---
if [ ! -d ".git" ]; then
    git init
    git branch -M main
fi

# --- Set remote ---
git remote remove origin 2>/dev/null
git remote add origin $REMOTE_URL

# --- Commit & Push ---
git add .
git commit -m "$COMMIT_MSG"
git push -u origin main

echo "✅ Script berhasil di-commit & di-push ke $REMOTE_URL"

# --- Generate loadstring Roblox ---
echo ""
echo "📄 Loadstring untuk Roblox:"
for file in *.lua; do
    echo "loadstring(game:HttpGet(\"https://raw.githubusercontent.com/fareltampan/farelanakpintar/main/$file\"))()"
done

